service: alarm-me
frameworkVersion: '2'

provider:
  name: aws
  region: ap-southeast-1
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  httpApi:
    metrics: true

functions:
  there:
    handler: handler.hello
    events:
      - httpApi:
          path: /there
          method: get

  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

resources:
  Resources:
    NotifyMe:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:service}-NotifyMe

    Api5xxAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        Namespace: AWS/ApiGateway
        MetricName: 5xx
        Dimensions:
          - Name: ApiId
            Value: !Ref HttpApi
          - Name: Stage
            Value: '$default'
          - Name: Resource
            Value: '/'
          - Name: Method
            Value: 'GET'
        Statistic: Sum
        ComparisonOperator: GreaterThanThreshold
        Threshold: 0
        Period: 60
        EvaluationPeriods: 1
        AlarmActions:
          - Ref: NotifyMe
