service: alarm-me-rest
frameworkVersion: '2'

provider:
  name: aws
  region: ap-southeast-1
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

resources:
  Resources:
    NotifyMe:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:service}-NotifyMe

    Api5xxAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        Namespace: AWS/ApiGateway
        MetricName: 5XXError
        Dimensions:
          - Name: ApiName
            Value: ${self:provider.stage}-${self:service}
        Statistic: Sum
        ComparisonOperator: GreaterThanThreshold
        Threshold: 0
        Period: 60
        EvaluationPeriods: 1
        AlarmActions:
          - Ref: NotifyMe
